/*Use case 1: Enter the training centre, halls, some bikes, some users, some trainers and trainings as mentioned above. This must be delivered as SQL*/

---------- Training centres ----------
insert into gyms (id, street_address, gym_name, gym_type, staffed) values
(1, 'Vangslundsgate 2', 'Øya', 'spinning', 0)
,(2, 'Loholt allé 81', 'Dragvoll', 'spinning', 1)
,(3, 'Chr. Frederiks gate 20', 'Gloeshaugen', 'regular', 1)
,(4, 'Moholt allmenning 12', 'Moholt', 'regular', 0);

---------- Halls ----------
insert into halls (id, gym_id, capacity) values
(1, 1, 20) /*Øya, 20 people*/
,(2, 1, 15) /*Øya, 15 people*/
,(3, 1, 25) /*Øya, 25 people*/
,(4, 2, 20) /*Dragvoll, 20 people*/
,(5, 2, 15) /*Dragvoll, 15 people*/
,(6, 2, 25) /*Dragvoll, 25 people*/
,(7, 3, 20) /*Gloshaugen, 20 people*/
,(8, 3, 15) /*Gloshaugen, 15 people*/
,(9, 3, 25) /*Gloshaugen, 25 people*/;

-- ,(10, 4, 10) /*Moholt, 20 people*/

---------- Facilities and gym facilities relationship ----------
/*May want to put staffed or unstaffed here?*/
insert into facilities (id, facility_name) values
(1, 'Individual training')
,(2, 'Weight training')
,(3, 'Endurance')
,(4, 'Sauna')
,(5, 'Group classes')
,(6, 'Yoga')
,(7, 'Squash')
,(8, 'Shower')
,(9, 'Wardrobes')
,(10, 'Climbing')
,(11, 'Spinning')
-- STAFFED?
;

insert into gym_facilities(gym_id, facility_id) values
-- Øya (PK: 1)
(1, 5)
,(1, 1)
,(1, 3)
,(1, 2)
,(1, 6)
,(1, 10)
,(1, 11)
,(1, 9)
,(1, 4)
,(1, 8)
-- Dragvoll (PK: 2)
,(2, 1)
,(2, 5)
,(2, 6)
,(2, 7)
,(2, 4)
,(2, 8)
,(2, 9)
-- Gløshaugen(PK: 3)
,(3, 1)
,(3, 5)
,(3, 2)
,(3, 6)
,(3, 3)
,(3, 8)
,(3, 4)
,(3, 9)
-- Moholt (PK: 4)
,(4, 1)
,(4, 2)
,(4, 3)
;

---------- Bikes ----------
insert into spinning_bikes(id, hall_id, bike_number, bluetooth_body_bike) values
-- Halls 1-3: In øya. I let Øya and Dragvoll have bluetooth body bikes
-- Hall 1
(1, 1, 200, 1)
,(2, 1, 201, 1)
,(3, 1, 202, 1)
-- Hall 2
,(4, 2, 200, 1)
,(5, 2, 201, 1)
,(6, 2, 202, 1)
-- Hall 3
,(7, 3, 200, 1)
,(8, 3, 201, 1)
,(9, 3, 202, 1)

-- Halls 4-6: Dragvoll.
-- Hall 4
,(10, 4, 200, 1)
,(11, 4, 201, 1)
,(12, 4, 202, 1)
-- Hall 5
,(13, 5, 200, 1)
,(14, 5, 201, 1)
,(15, 5, 202, 1)
-- Hall 6
,(16, 6, 200, 1)
,(17, 6, 201, 1)
,(18, 6, 202, 1)

-- Halls 7-9: Gløshaugen. Doesnt have bluetooth body bikes
-- Hall 7
,(19, 7, 200, 0)
,(20, 7, 201, 0)
,(21, 7, 202, 0)
-- Hall 8
,(22, 8, 200, 0)
,(23, 8, 201, 0)
,(24, 8, 202, 0)
-- Hall 9
,(25, 9, 200, 0)
,(26, 9, 201, 0)
,(27, 9, 202, 0)
;

---------- Users ----------
insert into users (id, first_name, last_name, email, phone_number, student) values
(1, 'Johnny', 'Nordmann', 'johnny@stud.ntnu.no', '40100001', 1)
,(2, 'Viola', 'Smith', 'viola@stud.ntnu.no', '40100010', 1)
/*Test users below are generated by AI*/
,(3, 'Erik', 'Hansen', 'erik.hansen@stud.ntnu.no', '40100002', 1)
,(4, 'Sara', 'Berg', 'sara.berg@stud.ntnu.no', '40100003', 1)
,(5, 'Lucas', 'Johansen', 'lucas.johansen@stud.ntnu.no', '40100004', 0)
,(6, 'Emma', 'Larsen', 'emma.larsen@stud.ntnu.no', '40100005', 1)
,(7, 'Noah', 'Dahl', 'noah.dahl@stud.ntnu.no', '40100006', 0)
,(8, 'Maja', 'Nilsen', 'maja.nilsen@stud.ntnu.no', '40100007', 1)
,(9, 'Oliver', 'Strand', 'oliver.strand@stud.ntnu.no', '40100008', 0)
,(10, 'Ingrid', 'Moen', 'ingrid.moen@stud.ntnu.no', '40100009', 1)
-- Users with NO bookings (control group) AI
,(11, 'Test', 'UserA', 'usera@stud.ntnu.no', '40100011', 1)
,(12, 'Test', 'UserB', 'userb@stud.ntnu.no', '40100012', 0)
,(13, 'Test', 'UserC', 'userc@stud.ntnu.no', '40100013', 1)
;

---------- Trainings ----------
/*
Currently instructors exist as an instructor_id referencing users here in group sessions

Group class descriptions not available in english on the page, might use AI to translate unless I have time to do it

*/
insert into activities (id, name, description) values
(1, 'Spin 4x4', 'An interval cycling session with a solid warm-up, followed by four standing intervals of 4 minutes each, with about 2 minutes of active recovery between efforts. The class ends with a cool-down.')
,(2, 'Spin 8x3min', 'An interval cycling session where you work in 3-minute intervals, alternating between standing and seated efforts. In total, there are 8 intervals, with 1.5 to 2 minutes of recovery between each. Warm-up and cool-down are included.')
,(3, 'Spin45', 'A cycling session with a varied profile divided into 2 to 3 work phases, suitable for everyone. You control the intensity yourself by adjusting the resistance.')
,(4, 'Spin60', 'A cycling session with a varied profile divided into 2 to 4 work phases. Slightly faster-paced with longer standing sections than Spin45, but you control the intensity by adjusting the resistance.')
,(5, 'Pump', "A full-body strength workout using a barbell, performed to music. Each exercise is done in 3 to 4 sets of 6 to 12 repetitions, with short breaks in between. You choose your own load by adjusting the weights. This class is ideal if you're new to strength training or want to focus on fundamental exercises.")
,(6, 'Ashtanga Yoga', "Ashtanga is a dynamic style of yoga where poses are performed in a set sequence. This class follows a modified version of the primary series. You should have some prior experience and be familiar with basic yoga principles before joining.")
,(7, 'Yoga Stretch', "A class focused on stretching and flexibility. We use yoga poses to work through the major muscle groups, aiming to release tension and open up tight areas in the body. The pace is calm, with poses held for longer periods. Suitable for all levels and ends with relaxation in savasana.")
,(8, 'Beatz', "A dance class where you move through song after song. Party music and dance styles are mixed together—bollywood, jazz, afro, house, funk, rave, girly pop, latino, hip hop, reggaeton, and more.")
,(9, 'StepMoves', "A step-based dance class combining choreography and movement patterns set to music. Level: intermediate to advanced. StepMoves is more challenging in terms of coordination and footwork compared to Step&Core (level 1).")
;

insert into group_sessions(id, activity_id, hall_id, instructor_id, start_time, end_time, signup_deadline, sessiondate) values
/*Halls 1-3 are at Øya, and halls 4-6 are at Dragvoll. I use only Viola, Maja and Emma (user id 2, 8, 6) as instructors
*/
-- 16.03.2026
(1, 2, 3, 2, '18:00:00', '18:45:00', '17:00:00', '2026-03-16') -- Spinning at Øya
,(2, 3, 6, 8, '16:00:00', '16:45:00', '15:00:00', '2026-03-16') -- Spinning at Dragvoll

-- 17.03.2026
,(3, 4, 1, 2, '18:30:00', '19:15:00', '17:30:00', '2026-03-17') -- Spinning at Øya. This is the activity in use case 2
,(4, 1, 5, 8, '17:00:00', '17:45:00', '16:00:00', '2026-03-17') -- Spinning at Dragvoll

-- 18.03.2026
,(5, 1, 2, 2, '19:00:00', '19:45:00', '18:00:00', '2026-03-18') -- Spinning at Øya
,(6, 3, 4, 8, '16:00:00', '16:45:00', '15:00:00', '2026-03-18') -- Spinning at Dragvoll

/*BELOW: Group session insertions generated by AI to fill more classes for some of the use cases */

-- ===== JANUARY =====

-- Week 2
,(7, 5, 7, 2, '17:00:00', '18:00:00', '16:00:00', '2026-01-12') -- Pump
,(8, 7, 8, 8, '18:30:00', '19:15:00', '17:30:00', '2026-01-13') -- Yoga Stretch
,(9, 8, 9, 6, '19:00:00', '20:00:00', '18:00:00', '2026-01-14') -- Beatz

-- Week 3
,(10, 6, 7, 2, '17:00:00', '18:30:00', '16:00:00', '2026-01-19') -- Ashtanga Yoga
,(11, 9, 8, 8, '18:00:00', '18:59:00', '17:00:00', '2026-01-20') -- StepMoves
,(12, 5, 9, 6, '16:30:00', '17:30:00', '15:30:00', '2026-01-21') -- Pump

-- Week 4
,(13, 7, 7, 2, '18:00:00', '18:45:00', '17:00:00', '2026-01-26') -- Yoga Stretch
,(14, 8, 8, 8, '19:00:00', '20:00:00', '18:00:00', '2026-01-27') -- Beatz
,(15, 6, 9, 6, '17:00:00', '18:30:00', '16:00:00', '2026-01-28') -- Ashtanga Yoga


-- ===== FEBRUARY =====

-- Week 6
,(16, 5, 7, 2, '17:00:00', '18:00:00', '16:00:00', '2026-02-09') -- Pump
,(17, 9, 8, 8, '18:00:00', '18:59:00', '17:00:00', '2026-02-10') -- StepMoves
,(18, 7, 9, 6, '19:00:00', '19:45:00', '18:00:00', '2026-02-11') -- Yoga Stretch

-- Week 7
,(19, 6, 7, 2, '17:00:00', '18:30:00', '16:00:00', '2026-02-16') -- Ashtanga Yoga
,(20, 8, 8, 8, '19:00:00', '20:00:00', '18:00:00', '2026-02-17') -- Beatz
,(21, 5, 9, 6, '16:30:00', '17:30:00', '15:30:00', '2026-02-18') -- Pump

-- Week 8
,(22, 7, 7, 2, '18:00:00', '18:45:00', '17:00:00', '2026-02-23') -- Yoga Stretch
,(23, 9, 8, 8, '18:00:00', '18:59:00', '17:00:00', '2026-02-24') -- StepMoves
,(24, 6, 9, 6, '17:00:00', '18:30:00', '16:00:00', '2026-02-25') -- Ashtanga Yoga
;

/*AI Generated hard coding of user bookings for January and February to test a few use cases*/
insert into session_bookings (session_id, user_id, booking_time) values

-- ===== JANUARY BOOKINGS =====

-- Session 7 (Pump)
(7, 1, '2026-01-10 12:00:00')
,(7, 3, '2026-01-11 10:00:00')
,(7, 4, '2026-01-11 11:00:00')

-- Session 8 (Yoga Stretch)
,(8, 1, '2026-01-12 09:00:00')
,(8, 6, '2026-01-12 12:00:00')
,(8, 7, '2026-01-12 13:00:00')

-- Session 9 (Beatz)
,(9, 5, '2026-01-13 15:00:00')
,(9, 8, '2026-01-13 16:00:00')
,(9, 9, '2026-01-13 17:00:00')

-- Session 10 (Ashtanga)
,(10, 1, '2026-01-17 10:00:00')
,(10, 3, '2026-01-18 11:00:00')

-- Session 11 (StepMoves)
,(11, 4, '2026-01-19 12:00:00')
,(11, 6, '2026-01-19 13:00:00')

-- Session 12 (Pump)
,(12, 1, '2026-01-20 14:00:00')
,(12, 7, '2026-01-20 15:00:00')

-- Session 13 (Yoga Stretch)
,(13, 8, '2026-01-25 10:00:00')
,(13, 9, '2026-01-25 11:00:00')

-- Session 14 (Beatz)
,(14, 3, '2026-01-26 12:00:00')
,(14, 4, '2026-01-26 13:00:00')

-- Session 15 (Ashtanga)
,(15, 5, '2026-01-27 14:00:00')
,(15, 6, '2026-01-27 15:00:00')


-- ===== FEBRUARY BOOKINGS =====

-- Session 16 (Pump)
,(16, 1, '2026-02-07 10:00:00')
,(16, 3, '2026-02-08 11:00:00')

-- Session 17 (StepMoves)
,(17, 4, '2026-02-08 12:00:00')
,(17, 8, '2026-02-08 13:00:00')

-- Session 18 (Yoga Stretch)
,(18, 6, '2026-02-09 14:00:00')
,(18, 7, '2026-02-09 15:00:00')

-- Session 19 (Ashtanga)
,(19, 1, '2026-02-14 10:00:00')
,(19, 9, '2026-02-14 11:00:00')

-- Session 20 (Beatz)
,(20, 5, '2026-02-15 12:00:00')
,(20, 8, '2026-02-15 13:00:00')

-- Session 21 (Pump)
,(21, 1, '2026-02-16 14:00:00')
,(21, 10, '2026-02-16 15:00:00')

-- Session 22 (Yoga Stretch)
,(22, 3, '2026-02-21 10:00:00')
,(22, 4, '2026-02-21 11:00:00')

-- Session 23 (StepMoves)
,(23, 6, '2026-02-22 12:00:00')
,(23, 7, '2026-02-22 13:00:00')

-- Session 24 (Ashtanga)
,(24, 8, '2026-02-23 14:00:00')
,(24, 9, '2026-02-23 15:00:00')
;
