/*Use case 1: Enter the training centre, halls, some bikes, some users, some trainers and trainings as mentioned above. This must be delivered as SQL*/

---------- Training centres ----------
insert into gyms (id, street_address, gym_name, gym_type, staffed) values
(1, 'Vangslundsgate 2', 'Øya', 'spinning', 0)
,(2, 'Loholt allé 81', 'Dragvoll', 'spinning', 1)
,(3, 'Chr. Frederiks gate 20', 'Gloeshaugen', 'regular', 1)
,(4, 'Moholt allmenning 12', 'Moholt', 'regular', 0);

---------- Halls ----------
insert into halls (id, gym_id, capacity) values
(1, 1, 20) /*Øya, 20 people*/
,(2, 1, 15) /*Øya, 15 people*/
,(3, 1, 25) /*Øya, 25 people*/
,(4, 2, 20) /*Dragvoll, 20 people*/
,(5, 2, 15) /*Dragvoll, 15 people*/
,(6, 2, 25) /*Dragvoll, 25 people*/
,(7, 3, 20) /*Gloshaugen, 20 people*/
,(8, 3, 15) /*Gloshaugen, 15 people*/
,(9, 3, 25) /*Gloshaugen, 25 people*/;

-- ,(10, 4, 10) /*Moholt, 20 people*/

---------- Facilities and gym facilities relationship ----------
/*May want to put staffed or unstaffed here?*/
insert into facilities (id, facility_name) values
(1, 'Individual training')
,(2, 'Weight training')
,(3, 'Endurance')
,(4, 'Sauna')
,(5, 'Group classes')
,(6, 'Yoga')
,(7, 'Squash')
,(8, 'Shower')
,(9, 'Wardrobes')
,(10, 'Climbing')
,(11, 'Spinning')
-- STAFFED?
;

insert into gym_facilities(gym_id, facility_id) values
-- Øya (PK: 1)
(1, 5)
,(1, 1)
,(1, 3)
,(1, 2)
,(1, 6)
,(1, 10)
,(1, 11)
,(1, 9)
,(1, 4)
,(1, 8)
-- Dragvoll (PK: 2)
,(2, 1)
,(2, 5)
,(2, 6)
,(2, 7)
,(2, 4)
,(2, 8)
,(2, 9)
-- Gløshaugen(PK: 3)
,(3, 1)
,(3, 5)
,(3, 2)
,(3, 6)
,(3, 3)
,(3, 8)
,(3, 4)
,(3, 9)
-- Moholt (PK: 4)
,(4, 1)
,(4, 2)
,(4, 3)
;

---------- Bikes ----------
insert into spinning_bikes(id, hall_id, bike_number, bluetooth_body_bike) values
-- Halls 1-3: In øya. I let Øya and Dragvoll have bluetooth body bikes
-- Hall 1
(1, 1, 200, 1)
,(2, 1, 201, 1)
,(3, 1, 202, 1)
-- Hall 2
,(4, 2, 200, 1)
,(5, 2, 201, 1)
,(6, 2, 202, 1)
-- Hall 3
,(7, 3, 200, 1)
,(8, 3, 201, 1)
,(9, 3, 202, 1)

-- Halls 4-6: Dragvoll.
-- Hall 4
,(10, 4, 200, 1)
,(11, 4, 201, 1)
,(12, 4, 202, 1)
-- Hall 5
,(13, 5, 200, 1)
,(14, 5, 201, 1)
,(15, 5, 202, 1)
-- Hall 6
,(16, 6, 200, 1)
,(17, 6, 201, 1)
,(18, 6, 202, 1)

-- Halls 7-9: Gløshaugen. Doesnt have bluetooth body bikes
-- Hall 7
,(19, 7, 200, 0)
,(20, 7, 201, 0)
,(21, 7, 202, 0)
-- Hall 8
,(22, 8, 200, 0)
,(23, 8, 201, 0)
,(24, 8, 202, 0)
-- Hall 9
,(25, 9, 200, 0)
,(26, 9, 201, 0)
,(27, 9, 202, 0)
;

---------- Users ----------
insert into users (id, first_name, last_name, email, phone_number, student) values
(1, 'Johnny', 'Nordmann', 'johnny@stud.ntnu.no', '40100001', 1)
,(2, 'Viola', 'Smith', 'viola@stud.ntnu.no', '40100010', 1)
/*Test users below are generated by AI*/
,(3, 'Erik', 'Hansen', 'erik.hansen@stud.ntnu.no', '40100002', 1)
,(4, 'Sara', 'Berg', 'sara.berg@stud.ntnu.no', '40100003', 1)
,(5, 'Lucas', 'Johansen', 'lucas.johansen@stud.ntnu.no', '40100004', 0)
,(6, 'Emma', 'Larsen', 'emma.larsen@stud.ntnu.no', '40100005', 1)
,(7, 'Noah', 'Dahl', 'noah.dahl@stud.ntnu.no', '40100006', 0)
,(8, 'Maja', 'Nilsen', 'maja.nilsen@stud.ntnu.no', '40100007', 1)
,(9, 'Oliver', 'Strand', 'oliver.strand@stud.ntnu.no', '40100008', 0)
,(10, 'Ingrid', 'Moen', 'ingrid.moen@stud.ntnu.no', '40100009', 1)
;

---------- Trainings ----------
/*
Currently instructors exist as an instructor_id referencing users here in group sessions

Group class descriptions not available in english on the page, might use AI to translate unless I have time to do it

*/
insert into activities (id, name, description) values
(1, 'Spin 4x4', 'Intervalltime på sykkel med god oppvarming, deretter 4 stående intervaller på 4 minutter med ca 2 minutter aktiv pause mellom hvert drag. Timen avsluttes med nedsykling.')
,(2, 'Spin 8x3min', 'Intervalltime på sykkel der du jobber i intervaller på 3 minutter og kjører annethvert drag stående og sittende. Totalt 8 intervaller, med 1.5-2 min pause mellom. Oppvarming og nedtrapping er inkludert i timen.')
,(3, 'Spin45', 'Spinningtime med variert løype fordelt på 2-3 arbeidsperioder som passer for alle. Du bestemmer selv intensiteten emd hvor mye motstand du legger på.')
,(4, 'Spin60', 'Spinningtime med variert løype fordelt på 2-4 arbeidsperioder. Litt raskere tempo og lengre stående perioder enn Spin45, men du bestemmer selv intensiteten med motstanden du legger på.')
;

insert into group_sessions(id, activity_id, hall_id, instructor_id, start_time, end_time, signup_deadline, sessiondate) values
/*Halls 1-3 are at Øya, and halls 4-6 are at Dragvoll.
*/
-- 16.03.2026
(1, 2, 3, 2, '18:00:00', '18:45:00', '17:00:00', '2026-03-16') -- Spinning at Øya
,(2, 3, 6, 8, '16:00:00', '16:45:00', '15:00:00', '2026-03-16') -- Spinning at Dragvoll

-- 17.03.2026
,(3, 4, 1, 2, '18:30:00', '19:15:00', '17:30:00', '2026-03-17') -- Spinning at Øya. This is the activity in use case 2
,(4, 1, 5, 8, '17:00:00', '17:45:00', '16:00:00', '2026-03-17') -- Spinning at Dragvoll

-- 18.03.2026
,(5, 1, 2, 2, '19:00:00', '19:45:00', '18:00:00', '2026-03-18') -- Spinning at Øya
,(6, 3, 4, 8, '16:00:00', '16:45:00', '15:00:00', '2026-03-18') -- Spinning at Dragvoll
;